-- Select base catalog chapter tree
WITH RECURSIVE
tr AS (
    SELECT NUMBER, NAME, CHAPTER_ID, PARENTCHAPTER_ID
  	    FROM BASECATALOGCHAPTER 
  	    WHERE CHAPTER_ID = (
            SELECT CHAPTER_ID
                FROM BASECATALOG
                WHERE VERSION = :VERSION
        )
    UNION ALL
    SELECT t.NUMBER, t.NAME, t.CHAPTER_ID, t.PARENTCHAPTER_ID
  	    FROM BASECATALOGCHAPTER t
  	    JOIN tr ON t.PARENTCHAPTER_ID = tr.CHAPTER_ID
)
SELECT NUMBER, NAME, CHAPTER_ID
FROM tr
ORDER BY NUMBER;